### ISSUE TITLE
Добавит у чернокнижника(варлок, лок) спелы: "Огонь и сера"

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#10]

**Comment by Demonist** [comment]
Углеотвод добавлен в 462f076e88b1596e2fbd9860d11f63b5a0aa6ab9. Огненный ливень уже был - необходимо перепроверить.

**Comment by daedalus91** [comment]
при заходе локом высветилось

Message: Interface\AddOns\SpellDamage\Data/Warlock.lua:9: attempt to perform arithmetic on field '?' (a nil value)
Time: 05/16/15 03:26:03
Count: 409
Stack: [C]: ?
Interface\AddOns\SpellDamage\Data/Warlock.lua:9: in function `computeFunc'
Interface\AddOns\SpellDamage\Data/Core.lua:185: in function`getData'
Interface\AddOns\SpellDamage\Data/Core.lua:231: in function `updateButton'
Interface\AddOns\SpellDamage\SpellDamage.lua:37: in function <Interface\AddOns\SpellDamage\SpellDamage.lua:14>

Locals:

**Comment by daedalus91** [comment]
Message: Interface\AddOns\SpellDamage\Data/Warlock.lua:9: attempt to perform arithmetic on field '?' (a nil value)
Time: 05/16/15 03:26:35
Count: 535
Stack: [C]: ?
Interface\AddOns\SpellDamage\Data/Warlock.lua:9: in function `computeFunc'
Interface\AddOns\SpellDamage\Data/Core.lua:185: in function`getData'
Interface\AddOns\SpellDamage\Data/Core.lua:231: in function `updateButton'
Interface\AddOns\SpellDamage\SpellDamage.lua:37: in function <Interface\AddOns\SpellDamage\SpellDamage.lua:14>

Locals:

**Comment by daedalus91** [comment]
Огненный ливень не появился

**Comment by daedalus91** [comment]
Углеотвод тоже

**Comment by Demonist** [comment]
Прикладывай скрины с описанием и id'шками. Так нихера не понятно.

**Comment by daedalus91** [comment]
![wowscrnshot_051715_115951](https://cloud.githubusercontent.com/assets/12463040/7669745/61abab78-fc8c-11e4-80f7-69529d38bd94.jpg)
![wowscrnshot_051715_115926](https://cloud.githubusercontent.com/assets/12463040/7669747/61aeb066-fc8c-11e4-8088-8142560a244a.jpg)
![wowscrnshot_051715_115915](https://cloud.githubusercontent.com/assets/12463040/7669746/61ad44b0-fc8c-11e4-8656-c92ab5ea6b2e.jpg)
![wowscrnshot_051715_115911](https://cloud.githubusercontent.com/assets/12463040/7669748/61af6e52-fc8c-11e4-810b-65da597fea18.jpg)

**Comment by daedalus91** [comment]
Не работаюст скилы:
Поджигание id - 17962
Огненный ливень id - 104232
Ожог Тьмы id - 17877
Углеотвод id  - 114635

**Comment by daedalus91** [comment]
![default](https://cloud.githubusercontent.com/assets/12463040/7669942/5d2bb0a8-fc95-11e4-9280-d4c3cce18b78.png)

**Comment by daedalus91** [comment]
![default](https://cloud.githubusercontent.com/assets/12463040/7669954/e737cd36-fc95-11e4-8006-c8df3b67a1c9.png)
![default](https://cloud.githubusercontent.com/assets/12463040/7669955/e804b986-fc95-11e4-8c6e-5238d2ecc249.png)

**Comment by Demonist** [comment]
Добавил еще один "Огненный ливень" в 7a39e7518aa59be359784d360404e73f07462119.

Временно изменил скиллы "Похищение жизни", "Углеотвод" и "MortalCoil". Они теперь отображают нули. Изменил чтобы убрать ошибки lua.

"Углеотвод" может отображать отрицательные значение - введено для отладки.

**Comment by Demonist** [comment]
"Похищение жизни" восстановлено в ca27dc358a2a7ec22f12e07f33ed4c0bb77d1ef3.
Так же восстановлен и исправлен "Лик тлена".

**Comment by daedalus91** [comment]
![default](https://cloud.githubusercontent.com/assets/12463040/7670964/5f0d90d0-fcc2-11e4-80c8-28f2735488ff.png)

**Comment by Demonist** [comment]
Наконец то исправлено в fe8705140348b2238a533f0692e0915b0e855827.

**Comment by daedalus91** [comment]
еще  лока добавит скилы, при бафе "огонь и сера"
![default](https://cloud.githubusercontent.com/assets/12463040/7671258/0112a2aa-fcd0-11e4-8f7d-17f45c2e699b.png)
![1](https://cloud.githubusercontent.com/assets/12463040/7671259/033aa8a2-fcd0-11e4-92f9-2d986c350092.png)
![default](https://cloud.githubusercontent.com/assets/12463040/7671260/06043468-fcd0-11e4-9610-2c765b50f673.png)

**Comment by Demonist** [comment]
Новые умения добавлены в 836caa393c7e49d678b288fe8b94d0c04139767d.
