### ISSUE TITLE
Охотник. Добавить скил "Выстрел хмеры". "Взрывная ловушка" не отображается в режиме метания.

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#13]

**Comment by Demonist** [comment]
Выстрел хмеры добавлен в 462f076e88b1596e2fbd9860d11f63b5a0aa6ab9. А вот что со взрывной ловушкой я хз - надо проверять.

**Comment by daedalus91** [comment]
Ловушка в режиме метния меняет свой Id.
Взрывная ловушка - 82939

**Comment by Demonist** [comment]
Добавил в 7a39e7518aa59be359784d360404e73f07462119.
