### ISSUE TITLE
Монах. "Танцующий журавль" в хиле имеет другое описание. Описание приложено.

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#15]
![default](https://cloud.githubusercontent.com/assets/12463040/7657186/c212c208-fb38-11e4-9fd5-41d2460e3469.png)

**Comment by Demonist** [comment]
Мне необходимо знать как меняется описание данного скилла в зависимости от набора специализаций.

**Comment by daedalus91** [comment]
Танцующий журавль хил
![default](https://cloud.githubusercontent.com/assets/12463040/7669786/b528cdce-fc8e-11e4-9787-e98709f74202.png)
Танцующий журавль танк
![default](https://cloud.githubusercontent.com/assets/12463040/7669789/bbab5b08-fc8e-11e4-8ccb-c47e553d1baf.png)

**Comment by daedalus91** [comment]
Не отображается способность "Дзуки" ID - 115698
И "Выброс Ци" ID - 123986

**Comment by daedalus91** [comment]
![default](https://cloud.githubusercontent.com/assets/12463040/7669880/70140172-fc93-11e4-85ff-7804f699cb47.png)

**Comment by Demonist** [comment]
Добавил еще один "Дзуки", исправил "Выброс Ци" в 7a39e7518aa59be359784d360404e73f07462119.

**Comment by daedalus91** [comment]
![wowscrnshot_052115_141101](https://cloud.githubusercontent.com/assets/12463040/7747466/561ca85e-ffc3-11e4-9cd1-311f42e16393.jpg)
Журавль в хиле так и не заработал.

**Comment by Demonist** [comment]
Танцующий журавль наконец то исправлен в 347f8b6f91079a69d54dfe14f7c60df0aa71bf41.
