### ISSUE TITLE
Проверить отображение "Неистовое восстановление" у друида.

### ISSUE THREAD

**Issue by Demonist** [Demonist/SpellDamage#16]
Интересует количество здоровья в описании.

**Comment by daedalus91** [comment]
![default](https://cloud.githubusercontent.com/assets/12463040/7657885/6311587c-fb3e-11e4-9325-b5926b8abb53.png)

**Comment by Demonist** [comment]
Необходимо выяснить как ото меняется в зависимости от набора специализаций.
На вскидку сделал в 462f076e88b1596e2fbd9860d11f63b5a0aa6ab9 так: если есть специализация ткача туманов, то скилл хиллит, иначе - дамажит.
