### ISSUE TITLE
Прист тьма, "Безумие" id 129197 "Полное безумие" id 179338

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#18]

**Comment by daedalus91** [comment]
![mykzqrrgrnm](https://cloud.githubusercontent.com/assets/12463040/7669976/8002c5f6-fc97-11e4-8fb6-a17bd029c4b3.jpg)
![5her2x_3fc8](https://cloud.githubusercontent.com/assets/12463040/7669977/80caa85a-fc97-11e4-9cd9-42a211b89f2e.jpg)

**Comment by daedalus91** [comment]
![default](https://cloud.githubusercontent.com/assets/12463040/7669978/86569932-fc97-11e4-809b-8cb23de3bfb4.png)
http://ru.wowhead.com/spell=179338
![default](https://cloud.githubusercontent.com/assets/12463040/7669979/8763b95e-fc97-11e4-8bb8-b8a1eeecff38.png)
http://ru.wowhead.com/spell=129197

**Comment by Demonist** [comment]
Вроде реализовал в 7a39e7518aa59be359784d360404e73f07462119.
