### ISSUE TITLE
Дк "Удар смерти" добаит хил и "Антимагический панцирь" добавить абсорб

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#19]
![default](https://cloud.githubusercontent.com/assets/12463040/7747388/adbb1f10-ffc2-11e4-8839-be9df9dfb31d.png)
![default](https://cloud.githubusercontent.com/assets/12463040/7747390/b1319cf0-ffc2-11e4-9faa-dbb60de39a24.png)

**Comment by daedalus91** [comment]
Ладно с панцирем перегнул... Чет не заметил что там % от урона, а не от хп

**Comment by Demonist** [comment]
Удар смерти исправлен в b1da1dca05d396bc498944d9d58a808901035666.
