### ISSUE TITLE
Жрец, скил "Обновление"

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#20]
![default](https://cloud.githubusercontent.com/assets/12463040/8038576/f390e634-0e0c-11e5-868e-8ad95c2f11f4.png)

**Comment by Demonist** [comment]
Реализовано в a622e3fc5c3b012cb559d66dc5d9d255519f7134.

**Comment by daedalus91** [comment]
Не работает обновление и слово света святилище.
![default](https://cloud.githubusercontent.com/assets/12463040/8087593/8b950580-0fa4-11e5-8da5-305bfdbb96ff.png)

**Comment by Demonist** [comment]
Святилище добавил в 26d79f7c1a4bd5d11c42bb16f99e8ccb6f624626.
А вот с обновлением хз что делать.

**Comment by Demonist** [comment]
Баг Blizzard'ов. Закрыто костылем в cbab4a517828435348882fc830821594032e6e70.
