### ISSUE TITLE
Вихрь

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#21]
![default](https://cloud.githubusercontent.com/assets/12463040/8039060/fd6009f8-0e0f-11e5-8bad-77b507785b69.png)

**Comment by daedalus91** [comment]
![default](https://cloud.githubusercontent.com/assets/12463040/8039179/a90f7a04-0e10-11e5-8c47-ff3a6aa59865.png)

**Comment by Demonist** [comment]
Реализовано в 9f01f89ec129300e1d6f13d0ffe1838d05188e66.

**Comment by Demonist** [comment]
Необходимо проверить корректность работы в различных специализациях.

**Comment by daedalus91** [comment]
В фури вихрь теперь вообще не отображается.

**Comment by Demonist** [comment]
Исправлено в 642f395e12b04075c69e1c800770050170f5a4fa.
