### ISSUE TITLE
Проверить умение "Ледяное копье" у мага.

### ISSUE THREAD

**Issue by Demonist** [Demonist/SpellDamage#22]
Необходимы сведения касательно изменения описания умения в зависимости от наличия умения "Ледяные пальцы" и символа "Символ ледяных осколков (Лед)".

**Comment by daedalus91** [comment]
![default](https://cloud.githubusercontent.com/assets/12463040/8068663/0894653c-0efe-11e5-8ef2-b0d46605e2b3.png)
![1](https://cloud.githubusercontent.com/assets/12463040/8068665/09a8a4f6-0efe-11e5-809a-80fb0ca68fc7.png)

**Comment by Demonist** [comment]
Все должно работать. Закрываю.
