### ISSUE TITLE
Вар ошибки в чате

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#29]
SpellDamage: Ошибка парсинга умения с id 1680 Вы кружитесь в вихре стали, атакуя всех противников в радиусе 8 м и нанося каждому из них 3404 ед. физического урона оружием в правой руке.
SpellDamage: Ошибка парсинга предмета с id 101618

случается после смены спека Фури на Прото, когда в руке 2 двуручных орудия

**Comment by Demonist** [comment]
Умение "Вихрь" должно быть исправлено в 11c11ad533c01e83749252a486ae0c33b7916d28, с предметом надо разбираться.
