### ISSUE TITLE
Взрывная волна

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#34]
"Взрывная волна" наносит на 100% больше урона если цель противник поскольку использование ее в союзников крайне редкий случай думаю можно увеличить отображаемый урон на панели.

**Comment by daedalus91** [comment]
Ну или отслеживать если нет цели или цель союзник то урон обычный, а если цель враг то урон увеличен на 100%

**Comment by Demonist** [comment]
Реализовано в d9f54790adda3607533481acecf24fa81d375726.
