### ISSUE TITLE
Соединение информации с CombustionHelper 

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#35]
Урон что считает  CombustionHelper отобразить на иконке "Возгорание"

**Comment by Demonist** [comment]
Поподробнее пожалуйста. Какие именно цифры нужно отображать?

**Comment by daedalus91** [comment]
![84d1c366b25e22ff1fc6bcf9106ccd6b](https://cloud.githubusercontent.com/assets/12463040/8542162/4bc3a648-249c-11e5-9d6c-3fcde7dbe1b3.png)
последнее значение

**Comment by daedalus91** [comment]
![default](https://cloud.githubusercontent.com/assets/12463040/8542656/f972f4d0-249f-11e5-85be-3faf9642f0d7.png)
значение после "Tiсk:"
сколько тиков отображать не надо.

**Comment by Demonist** [comment]
Вроде реализовал в ed83d6af0ce1b225b9d89d81800e1455cc39bc35.
