### ISSUE TITLE
Похищение жизни поломалось, скрин ниже

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#36]
![default](https://cloud.githubusercontent.com/assets/12463040/8622596/ffca8270-2734-11e5-8a8a-088a47366467.png)

**Comment by Demonist** [comment]
Ну ты хотя б написал чей скилл то...

**Comment by Demonist** [comment]
Пофиксено в 118fb3e7dc6d72aa14e1462134460a98df0f320d.
