### ISSUE TITLE
Монах, Дзуки

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#38]
Не отображается при ношении молотков.(ибо скил меняется)
![default](https://cloud.githubusercontent.com/assets/12463040/8705488/974cd4b2-2b32-11e5-89f1-27c94952298e.png)

**Comment by daedalus91** [comment]
Собсно у себя сам добавил, в версии на сайте добавь только

**Comment by Demonist** [comment]
Реализовал в 8704f1d932ff0cebdf71cf95d0a206355c4c6fc1.
