### ISSUE TITLE
Паладин, некорректное отображение способности "Испепеляющий след", подробно внутри

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#52]
Умение испепелителя отображается некорректно id 205273, скрины прилагаются.
![default](https://cloud.githubusercontent.com/assets/12463040/18164280/baa2763c-7047-11e6-918b-fa7a2a8edc03.png)
![default](https://cloud.githubusercontent.com/assets/12463040/18164281/baa2f288-7047-11e6-80ad-90f516cb67da.png)

**Comment by Demonist** [comment]
Исправлено в 2.0.8.0-beta (cab7bff7f64412d66416edad93d0ccfafc29f17d).
