### ISSUE TITLE
Жрец, нет отображения урона на заклинании "Темное востановление" id 186253

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#54]
![default](https://cloud.githubusercontent.com/assets/12463040/18164466/b0d8191c-7048-11e6-8d30-f00581fc107d.png)

**Comment by Demonist** [comment]
Я считаю что урон не должен отображаться т.к. это урон в дружественную цель, а аддон отображает урон по противнику.

**Comment by Demonist** [comment]
Добавлено 2.0.8.0-beta (cab7bff7f64412d66416edad93d0ccfafc29f17d).
