### ISSUE TITLE
Маг, некорректное отображение заклинания "Огненный столб" при таланте "Огненный след"

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#56]
При использовании таланта "Огненный след" id 205037, у заклинания "Огненный столб" id 2120 появляется урон со временем(на подобии таланта заклинания "Метеор"), но текст об этом не добавляется в само описание способности "Огненный столб"
Огненный след:
![default](https://cloud.githubusercontent.com/assets/12463040/18164947/5840ae7e-704b-11e6-8a13-909d057de17c.png)
Огненный столб:
![default](https://cloud.githubusercontent.com/assets/12463040/18164957/60c2c528-704b-11e6-8835-051cab5df0ef.png)

**Comment by Demonist** [comment]
Исправлено в 2.0.8.0-beta (cab7bff7f64412d66416edad93d0ccfafc29f17d).
