### ISSUE TITLE
Маг, некорректное отображение заклинания "Ледяная глыба" при таланте "Холодная хватка"

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#57]
При выбранном таланте "Холодная хватка" id 11958 у способности "Ледяная глыба" id 45438 появляется периодическое лечение, но в тексте способности "Ледяная глыба" не добавляется описание этого.
Холодная хватка:
![default](https://cloud.githubusercontent.com/assets/12463040/18165257/edc2b4dc-704c-11e6-9970-2e3952e407e0.png)
Ледяная глыба:
![default](https://cloud.githubusercontent.com/assets/12463040/18165281/0319557a-704d-11e6-9ce1-d939a2918f79.png)

**Comment by Demonist** [comment]
Добавлено в версии 2.0.8.0-beta (cab7bff7f64412d66416edad93d0ccfafc29f17d).
