### ISSUE TITLE
Охотник на демонов, отображение лечение от поглощения "Фрагменты души"

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#63]
Способность "Иссечение" (id 203782):
![default](https://cloud.githubusercontent.com/assets/12463040/18844466/042146c0-8426-11e6-99c0-fafbd5c940db.png)
Способность "Раскалывание душ" (id 228477):
![default](https://cloud.githubusercontent.com/assets/12463040/18844551/5a9b78ea-8426-11e6-8263-8d10d6560110.png)
Баф на игроке "Фрагменты души" (id 203981):
![default](https://cloud.githubusercontent.com/assets/12463040/18844591/87d12b8e-8426-11e6-88e0-63de8690794b.png)

При использование способности "Иссечение" генерируются Фрагменты душ (количество фрагментов отображается в бафе "Фрагменты души") которые добавляют исцеление( количество исцеления фрагмента души описаны в способности "Иссечение") за каждый фрагмент души(эффект от сфер суммируется от количества сфер в бафе "Фрагменты души") в способность "Раскалывание душ".

**Comment by Demonist** [comment]
Исправлено в ebe332f96d8cbba2f76dc76fdf6396e6c9088916 (2.0.14.0).
