### ISSUE TITLE
Unable to parse SID #116670

### ISSUE THREAD

**Issue by Dajova** [Demonist/SpellDamage#68]
Doesn't seem to like the "new" Vivify.

![SD](https://i.imgur.com/JQUNI8t.png)

https://www.wowhead.com/spell=116670/vivify

**Comment by Dajova** [comment]
More SpellID spam... 
![SD](https://i.imgur.com/e54lTOO.png)

**Comment by daedalus91** [comment]
I hope that was it fixed in 2.2.1.1 version. If some mistakes occur in chat window, please check dev mode status using /sd status command. If dev mode is active please turn it off using /sd dev command.
