### ISSUE TITLE
Добавить "Яростный выпад" и "Непроницаемый щит" у вара

### ISSUE THREAD

**Issue by daedalus91** [Demonist/SpellDamage#9]

**Comment by Demonist** [comment]
Яростный выпад исправлен. А вот с Непроницаемым щитом я хз. У меня все вроде норм. Проверь еще раз.

**Comment by daedalus91** [comment]
Непроницаемый щит так и не заработал

**Comment by Demonist** [comment]
Напиши id'шку скилла.

P.S.: На будущее, если умение косячит - пиши сразу его id.

**Comment by daedalus91** [comment]
Непроницаемый щит id - 112048

**Comment by Demonist** [comment]
Добавил в 7a39e7518aa59be359784d360404e73f07462119.
